### ISSUE TITLE
Yarn start error

### ISSUE THREAD

**Issue by onlynexd** [5elfle5/coinflip-bet#3]
![image](https://user-images.githubusercontent.com/106020262/186249711-76ac31ba-66cb-4c96-81d9-e3b2bdb4c792.png)

Can u help me pls?

**Comment by 5elfle5** [comment]
I'm sorry, this looks too generic for me to have any ideas

**Comment by 5elfle5** [comment]
I cannot help, sorry

**Comment by 5elfle5** [comment]
Cannot help, sorry
